### PR TITLE
Travis and nosetests

### PR DESCRIPTION
**Pull request by knelasevero**
```
Signed-off-by: Caio Nardelli <caio.nardelli@hotmail.com>
Signed-off-by: Daniel Henrique <danielhmarinho@gmail.com>
Signed-off-by: Lucas Severo <lucassalves65@gmail.com>
```

### CODE REVIEW

**Comment by knelasevero** [comment]
merge this after the ssl cert pr.

**Comment by lucaskanashiro** [comment]
Rebase it with master branch please.

**Comment by aldarionsevero** [comment]
Rebased, but a new rebase has to be done after accepting the ssl-fix MR

**Comment by lucaskanashiro** [comment]
I checked out to your branch, provisioned the VM again (vagrant provision), logged in the VM (vagrant ssh), ran the tests and I got the error bellow:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/vagrant/test/test_models.py", line 6, in <module>
    from mock import MagicMock
ImportError: No module named mock

I guess you need to add this new dependency (mock) in chef's recipe. Fix it in #24 should be ok.

**Comment by lucaskanashiro** [comment]
This PR contains this one #24 ? If yes you should close it.

**Comment by knelasevero** [comment]
added the mock module install in the recipe.

**Pull request merged**
