### PR TITLE
Ssl fix and tests

### PR DESCRIPTION
**Pull request by knelasevero**

### CODE REVIEW

**Comment by knelasevero** [comment]
Now if an engine cant be created, we raise the exception @lucaskanashiro. I will wait for the flake8 pr to be fixed, and after the rebases, we can merge it.

**Comment by knelasevero** [comment]
Merge this after the flake8 pr.

**Comment by lucaskanashiro** [comment]
I think that you have a typo in your commit message @aldarionsevero , you should mean ssl instead of ssh.

**Comment by knelasevero** [comment]
Oh, sorry. Now it's fixed.

**Comment by lucaskanashiro** [comment]
Rebase it with master please

**Comment by knelasevero** [comment]
Rebased.

**Comment by knelasevero** [comment]
added the mock module install here

**Comment by lucaskanashiro** [comment]
You need to run flake8 before send a pull request. I can find these warnings executing flake8 in files that you modified:

./test/test_models.py:29:13: F841 local variable 'engine' is assigned to but never used
./test/test_models.py:30:44: E231 missing whitespace after ','
./test/test_models.py:42:13: F841 local variable 'engine' is assigned to but never used
./test/test_models.py:43:44: E231 missing whitespace after ','
./test/test_models.py:44:1: W391 blank line at end of file

**Comment by lucaskanashiro** [comment]
I tested all the executable scripts that we have in our project's root directory and I think that we can add a try except block in pet-update (the line bellow):

`pet.sql.DBUpdater().run(engine=pet.engine(options.no_cert), create_database=options.create)`

Because if the user do not pass -nc flag and do not have a valid certificate the OperationalError exception is thrown. We can handle it and notify user that he/she needs a certificate or should pass -nc flag.

**Pull request merged**
