### PR TITLE
Updating README and putting general license

### PR DESCRIPTION
**Pull request by TiagoAssuncao**
- Putting vagrant on readme
- Putting update repository
- rename to README.md
- tracking of coverage and build in readme

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
@TiagoAssuncao you should instruct potential contributors to use vagrant from Debian repository instead of upstream site :)

And you can edit th commit message just to 'Update README', and if you want to specify the license you can use 'setting general license' instead of 'putting'.

**Comment by TiagoAssuncao** [comment]
Now is ok?
If yes, i will change commit's name.

**Comment by lucaskanashiro** [comment]
@TiagoAssuncao are you sure that you just updated README? Because you have 10 modified files. And I want just one commit with this modification, you must squash your commits.

**Comment by TiagoAssuncao** [comment]
Yes. I just updated the README and added the copying file, others files are the rebase. And I will squash the commits when you aprove the changes.

**Comment by danielhmarinho** [comment]
This issue was updated so now this should be reviewed, revised and merged.
@lucaskanashiro

**Pull request merged**
