### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by victorcabeceira**
Applying flake8 on the whole project, as well as a basic flake8 configuration file.

### CODE REVIEW

**Comment by lucasmoura** [comment]
Can you please tell which flake8 version you are using ? With flake8 2.5.4 some warnings are still left in the code:

./**init**.py:18:1: E302 expected 2 blank lines, found 1
./**init**.py:19:3: E111 indentation is not a multiple of four
./**init**.py:19:81: E501 line too long (140 > 80 characters)
./classifier.py:47:9: F841 local variable 'highest_tag' is assigned to but never used
./perlre.py:68:1: C901 'apply_perlre' is too complex (22)
./vcs.py:136:9: F841 local variable 'root' is assigned to but never used
./vcs.py:149:1: C901 'Subversion.changed_named_trees' is too complex (25)
./vcs.py:330:1: C901 'Git.changed_named_trees' is too complex (15)
./watch.py:56:1: C901 'WatchRule.parse' is too complex (20)
./watch.py:195:1: C901 'Watcher.check' is too complex (12)
./watch.py:225:1: C901 'Watcher.check_rule' is too complex (16)
./web/views.py:23:1: F401 'HTTPBadRequest' imported but unused
./web/views.py:27:1: F401 're' imported but unused
./web/views.py:77:5: F841 local variable 'repo_name' is assigned to but never used

**Comment by lucasmoura** [comment]
Secondly, it would be better if you break your commit into each directory you have fixed flake8. For example:

Fix flake8 for web folder files

Would be a commit containing all the flake8 fixes for web files. If you make commits like that it will be easier to review your merge request, because one person can review one folder while someone else reviews another one for example :)

**Comment by lucaskanashiro** [comment]
I tell them to squash the commits, because they have a several commits. Your suggestion is a good approach, but if this generate some overhead for you guys you can leave this way :) do you agree @lucasmoura?

**Comment by lucasmoura** [comment]
No problem :)

**Comment by victorcabeceira** [comment]
I am using flake8 version 2.5.4 and some of those errors are due to a configuration that we had put in order to check the complexity of the code, but it should have been removed. The others errors are generally related to imported libraries and/or variables assigned and never used, and we decided not to remove them because we could not know if they would be necessary. @lucasmoura We did not break the commits in folders as a recommendation from @lucaskanashiro and because the whole commit is only about flake8.
I am going to fix these and commit. Also, the branch master already has some of these fixed.

**Comment by danielhmarinho** [comment]
We discover a problem when we start the application, so we'll improve this.

**Comment by lucaskanashiro** [comment]
What is the status of this task?

**Comment by victorcabeceira** [comment]
There is only one flake8 error not yet solved. If we fix it according to the pep8, the system stops working. We rebased it to the master and posteriorly refactor the part of the code related to this error.

**Pull request merged**
